lib/chitchat_web/router.ex
defmodule ChitchatWeb.Router do
  use ChitchatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChitchatWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/rooms", RoomController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChitchatWeb do
  #   pipe_through :api
  # end
end

lib/chitchat/application.ex
defmodule Chitchat.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      cluster_supervisor(),
      # Start the endpoint when the application starts
      ChitchatWeb.Endpoint
      # Starts a worker by calling: Chitchat.Worker.start_link(arg)
      # {Chitchat.Worker, arg},
    ] |> Enum.filter(& &1)

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Chitchat.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ChitchatWeb.Endpoint.config_change(changed, removed)
    :ok
  end

  defp cluster_supervisor do
    case Application.get_env(:libcluster, :topologies) do
      nil -> nil
      topologies -> {Cluster.Supervisor, [topologies, [name: Chitchat.ClusterSupervisor]]}
    end
  end

end

lib/chitchat_web/controllers/page_controller.ex
defmodule ChitchatWeb.PageController do
  use ChitchatWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/chitchat_web/controllers/room_controller.ex
defmodule ChitchatWeb.RoomController do
  use ChitchatWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def show(conn, %{"id" => room}) do
    render(conn, "show.html", room: room)
  end
end

lib/chitchat_web/views/error_view.ex
defmodule ChitchatWeb.ErrorView do
  use ChitchatWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/chitchat_web/views/layout_view.ex
defmodule ChitchatWeb.LayoutView do
  use ChitchatWeb, :view
end

lib/chitchat_web/views/page_view.ex
defmodule ChitchatWeb.PageView do
  use ChitchatWeb, :view
end

lib/chitchat_web/views/room_view.ex
defmodule ChitchatWeb.RoomView do
  use ChitchatWeb, :view
end

lib/chitchat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Chitchat · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/chitchat_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

lib/chitchat_web/templates/room/index.html.eex
<h1>Lobby</h1>
<%= form_tag Routes.room_path(@conn, :index), [method: :get, id: "roomPicker"] do %>
  <%= tag :input, name: "room" %>
  <%= content_tag :button, "Enter Room", type: "submit" %>
<% end %>

<script>
$(function() {
  $('#roomPicker').on('submit', function(event) {
    event.preventDefault();
    var url = $(event.target).attr('action');
    var room = $(event.target).find('input[name="room"]').val();
    window.location.href = url + '/' + room;
  })
})
</script>

lib/chitchat_web/templates/room/show.html.eex
<p class="alert alert-warning">
  Successfully joined room <b id="room"></b> on node <b id="node"></b>
</p>

<div id="messagesContainer"></div>

<form id="messageForm">
  <input id="messageInput"/>
  <button>Send</button>
</form>

<script>
$(function() {
  var channel = socket.channel('room:<%= @room %>', {});
  channel.join().receive("ok", function(payload) {
    $('#room').text(payload.room);
    $('#node').text(payload.node);
  });
  channel.on('shout', function(payload) {
    $('<p class="alert alert-info"/>').text(payload.text).appendTo('#messagesContainer');
  });

  $('#messageForm').on('submit', function(event) {
    event.preventDefault();
    var text = $('#messageInput').val();
    if (text) {
      channel.push('shout', {text: text});
      $('#messageInput').val('');
    }
  });
})
</script>